version: "3.7"

services:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_INSTALL_PLUGINS=volkovlabs-echarts-panel
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana  
      - ./plugins.txt:/plugins.txt
      - grafana_plugins:/var/lib/grafana/plugins

volumes:
  grafana_data:
  grafana_plugins:  


      # - GF_INSTALL_PLUGINS=volkovlabs-echarts-panel
      # - GF_INSTALL_PLUGINS=grafana-infinity-datasource
      # - GF_INSTALL_PLUGINS=grafana-json-datasource

      # - GF_INSTALL_PLUGINS=grafana-infinity-datasource,volkovlabs-echarts-panel,grafana-json-datasource
