version: "3.4"

services:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
    # volumes:
      # - ./provisioning:/etc/grafana/provisioning

